[pytest]
DJANGO_SETTINGS_MODULE = project.settings.base
python_files = tests.py test_*.py *_tests.py
addopts = -v

env =
    DATABASE_URL=sqlite:///:memory:
    DEBUG=True
    SECRET_KEY="django-insecure-minimum-32-characters-long-secret-key-value"
