# Generated by Django 6.0.7 on 2026-08-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="startupprofile",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
