# Generated by Django 6.0.7 on 2026-08-19 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0005_startupprofile_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startupprofile",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: '+380XXXXXXXXX'.",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
        ),
    ]
