# Generated by Django 6.0.7 on 2026-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_about_html_user_contact_email_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.URLField(max_length=500),
        ),
    ]
